apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: helloworld.ibm.com
    http:
      paths:
        - path: /
          backend:
            serviceName: app-svc
            servicePort: 8080
